vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,ru.viz.clinic.request
  launch-browser: true
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: false
  mustache:
    check-template-location: false
  datasource:
    username: root
    password: ${viz-clinic.db-pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${viz-clinic.db-host}:${viz-clinic.db-port}/${viz-clinic.db-name}?createDatabaseIfNotExist=true
  sql:
    init:
      mode: always
  mail:
    host: ${viz-clinic.mail-host}
    port: ${viz-clinic.mail-port}
    username: ${viz-clinic.mail-user}
    password: ${viz-clinic.mail-pass}
    test-connection: true
    protocol: smtps
    properties:
      mail:
        smtp:
          socketFactory:
            port: ${viz-clinic.mail-port}
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          timeout: 5000
          writetimeout: 5000
    sender: # отправитель письма (его почта и имя)
      email: ${viz-clinic.mail-user}
      text: no-reply


viz-clinic:
  mail-host: ${MAIL_HOST:smtp.yandex.ru}
  mail-port: ${MAIL_PORT:465}
  mail-user: ${MAIL_USER:dimitrijmackert@yandex.ru}
  mail-pass: ${MAIL_PASS:NTheJAhVSK5rp_m}

server:
  port: ${PORT:8080}

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: none

viz-clinic:
  db-port: ${DB_PORT:3306}
  db-host: ${DB_HOST:127.0.0.1}
  db-pass: ${DB_PASS:mau}
  db-name: ${DB_NAME:viz_clinic_db_local}

---
spring:
  config:
    activate:
      on-profile: local_new_db
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      schema-locations: classpath:data_local.sql
    default-encoding: UTF-8

viz-clinic:
  db-port: ${DB_PORT:3306}
  db-host: ${DB_HOST:127.0.0.1}
  db-pass: ${DB_PASS:mau}
  db-name: ${DB_NAME:viz_clinic_db_local}

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: none

viz-clinic:
  db-port: ${DB_PORT:3306}
  db-host: ${DB_HOST:172.20.128.2}
  db-pass: ${DB_PASS:mau}
  db-name: ${DB_NAME:viz_clinic_db_test}




  #  ssl:
  #    key-store-type: PKCS12
  #    key-store: classpath:keystore/vizclinic.p12
  #    key-store-password: test1234
  #    key-alias: vizclinic
  #    enabled: true
  #trust:
  #  store: classpath:keystore/vizclinic.p12
  #  store-password: test1234