vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,ru.viz.clinic.request
  launch-browser: true
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
  mustache:
    check-template-location: false
  datasource:
    username: root
    password: ${viz-clinic.db-pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${viz-clinic.db-host}:${viz-clinic.db-port}/${viz-clinic.db-name}?createDatabaseIfNotExist=true
  sql:
    init:
      mode: always
logging:
  level:
    org:
      atmosphere: warn

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      schema-locations: classpath:data_local.sql
server:
    port: ${PORT:8081}

viz-clinic:
  db-port: ${DB_PORT:3306}
  db-host: ${DB_HOST:127.0.0.1}
  db-pass: ${DB_PASS:mau}
  db-name: ${DB_NAME:viz_clinic_db_local}

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      schema-locations: classpath:data_test.sql

viz-clinic:
  db-port: ${DB_PORT:3306}
  db-host: ${DB_HOST:127.0.0.1}
  db-pass: ${DB_PASS:mau}
  db-name: ${DB_NAME:viz_clinic_db_test}
  
server:
  port: ${PORT:8082}

